---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-disk-loss-sa
  namespace: default
  labels:
    name: azure-disk-loss-sa
    app.kubernetes.io/part-of: litmus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: azure-disk-loss-sa
  namespace: default
  labels:
    name: azure-disk-loss-sa
    app.kubernetes.io/part-of: litmus
rules:
  - apiGroups: [""]
  resources: ["pods","events","secrets"]
  verbs: ["create","list","get","patch","update","delete","deletecollection"]
  - apiGroups: [""]
    resources: ["pods/exec","pods/log"]
    verbs: ["create","list","get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create","list","get","delete","deletecollection"]
  - apiGroups: ["litmuschaos.io"]
    resources: ["chaosengines","chaosexperiments","chaosresults"]
    verbs: ["create","list","get","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-disk-loss-sa
  namespace: default
  labels:
    name: azure-disk-loss-sa
    app.kubernetes.io/part-of: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: azure-disk-loss-sa
subjects:
- kind: ServiceAccount
  name: azure-disk-loss-sa
  namespace: default